### ISSUE TITLE
How to add mathjax to index.html

### ISSUE THREAD

**Issue by zmonoid** [sinedied/backslide#10]
as titled.

**Comment by zmonoid** [comment]
I have tried to add the following code to index.html inside body block. However it does not work.

```html
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML&delayStartupUntil=configured" type="text/javascript"></script>
    <script>
      var slideshow = remark.create();

      MathJax.Hub.Config({
          tex2jax: {
          skipTags: ['script', 'noscript', 'style', 'textarea', 'pre']
          }

      });
      MathJax.Hub.Queue(function() {
          $(MathJax.Hub.getAllJax()).map(function(index, elem) {
              return(elem.SourceElement());
          }).parent().addClass('has-jax');
      });
      MathJax.Hub.Configured();
    </script>
    <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        tex2jax: {inlineMath: [["$","$"],["\\(","\\)"],["\[","\]"]]},
      });
    </script>
```

**Comment by sinedied** [comment]
See https://github.com/sinedied/backslide/issues/5

**Comment by zmonoid** [comment]
Thanks very much.

The problem is that rendering MathJax is really slow than directly using remarkjs

**Comment by zmonoid** [comment]
It seems the math will be rendered randomly...

Sometime it even does not work!

**Comment by sinedied** [comment]
Not really a backslide related issue then. It's maybe your network, since MathJax loads a bunch of files, is quite heavy and cannot be inlined to work offline.

You should try [KaTeX](https://github.com/Khan/KaTeX).

**Comment by zmonoid** [comment]
Thanks very much. KaTex is much faster indeed.
I am currently facing problem with both mathjax and katex, which should be a problem of remarkjs, and I reported here:

https://github.com/gnab/remark/issues/464

**Comment by sinedied** [comment]
I'll close the issue then, thanks for the feedback.
