### ISSUE TITLE
Add support for setting a default style.scss

### ISSUE THREAD

**Issue by bajabob** [sinedied/backslide#12]
From either the init process or another backslide command, it would be wonderful if we could set a default style for all presentations that are created from that point forward. Possibly even defining a theme so that the user could specify, ```bs init --theme my-theme-name```.

**Comment by sinedied** [comment]
Nice idea, I'll take a look at this.
I'm thinking of going even further, allowing to override not only the theme but the whole template, including html/js if needed.

**Comment by wojtekkutylacc** [comment]
That would be incredibly useful.

**Comment by sinedied** [comment]
This feature is now available in `2.1.0`.

**Comment by bajabob** [comment]
Well done @sinedied, thank you!

**Comment by wojtekkutylacc** [comment]
👍
