### ISSUE TITLE
Errors when installing on Windows 10

### ISSUE THREAD

**Issue by yzhang-gh** [sinedied/backslide#15]
I get this after run `npm install -g backslide`

```
npm ERR! hummus@1.0.82 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hummus@1.0.82 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hummus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
```

and the root cause

```
gyp ERR! stack Error: Can't find Python executable "C:\Users\zhang\Anaconda3\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (C:\Users\zhang\AppData\Roaming\npm\node_modules\backslide\node_modules\node-gyp\lib\configure.js:483:19)
```

But I do have `C:\Users\zhang\Anaconda3\python.exe` and have my env variables set correctly (because I can enter the Python REPL by typing `python` in the CMD).

Could you please help me have a look?

**Comment by sinedied** [comment]
Someone encountered this error once when trying to install behind a corporate proxy.
For some reasons it seems that the `hummus` package can't manage to download its prebuilt binaries, causing the error your are seeing.
Could you try installing behind a direct internet connection?

**Comment by yzhang-gh** [comment]
Tried without proxy but it seems not to be the cause.

Then I searched "hummus node-pre-gyp install --fallback-to-build" on Google and found a solution

`npm install -g node-gyp`
`npm install --global --production windows-build-tools` (for Windows users)

And then run `npm install -g backslide`. The error is still there (it is expected on Windows) but the installation will continue.

---

But the new problem is `ERROR: Failed to download Chromium r499413` when installing package `puppeteer` 😵

**Comment by yzhang-gh** [comment]
It seems that I finally get it installed. Thank you.

But when I use `bs init`, it says

```
fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\zhang\AppData\Roaming\npm\node_modules\backslide\node_modules\node-sass\vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    ...
```

I know little about Sass. Does it mean I need to install Sass first?

**Comment by sinedied** [comment]
Seems that you have issues with modules that have native bindings. Sass is normally installed with everything else, you should have nothing extra to install beside NodeJS (I just checked in a fresh Windows 10 VM).

You can try `npm rebuild node-sass` to see if it fixes your error.

Which NodeJS/NPM version are your using?

**Comment by yzhang-gh** [comment]
I'm away from my laptop now and will try again later.

**Comment by yzhang-gh** [comment]
After reinstallation it works. The second problem is just caused by the network.
