### ISSUE TITLE
How to use remarks-plugin

### ISSUE THREAD

**Issue by matclab** [sinedied/backslide#24]
I tried to use some remarkjs plugins (such as [remark-toc](https://github.com/remarkjs/remark-toc) with backslide), but it is not clear how plugins may be called, because the remark.js inside backslide doesn't seem to provide a `use()` function.

If you have some tips or indication on how to proceed, do not hesitate to share.

**Comment by sinedied** [comment]
You're confusing this [Remark](https://github.com/gnab/remark), the lib to make slides using markdown with [this other Remark](https://github.com/remarkjs/remark) which is markdown parser. That's why you cannot use your plugins, as it's aimed for the second one 😉

**Comment by matclab** [comment]
Oups, my bad.

Thanks for pinpointing the confusion.
