### ISSUE TITLE
No LaTex?

### ISSUE THREAD

**Issue by JnuLi** [sinedied/backslide#28]
Does this not support latex?

**Comment by sinedied** [comment]
I guess you want math formulas, not really latex? See https://github.com/sinedied/backslide/issues/10 for Mathjax / Katex integration

**Comment by JnuLi** [comment]
Okay，thank you

**Comment by JnuLi** [comment]
How to add Katex, though'katex.tar.gz'is downloaded, but I don't know how to use it.

Trying to use #4 and #10, but did not find a complete solution. Could you give us a tutorial?

**Comment by sinedied** [comment]
You can take a look at the RemarkJS wiki: https://github.com/gnab/remark/wiki/LaTeX-Using-KaTeX
