### ISSUE TITLE
Export to HTML breaks relative paths

### ISSUE THREAD

**Issue by wtbarnes** [sinedied/backslide#29]
## OS and Version Info
macOS 10.12.6 (Sierra)
node v6.10.3
backslide v2.3.0

## Problem
It seems that when exporting slides to HTML, the relative paths to images, any local JS files, etc. are broken. For example, if the `/path/to/my_slides/template/index.html` file looks like, 

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>{{title}}</title>
  {{{style}}}
  <script src="remark.min.js"></script>
  <!-- Rest of file here -->
```

and I export my slides to a new directory,

```shell
$ bs e -l -r -o /path/to/my_output_dir
```

the file `/path/to/my_output_dir/presentation.html` looks like,

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>My Title</title>
  <style>
  <!-- Styling stuff here -->
  </style>
  <script src="file:///path/to/my_slides/template/remark.min.js"></script>
<!-- Rest of file here -->
```

**The path to the Remark JS source is converted to an absolute path and this path is to the original location of the file, not the path to the exported source.** This happens with image paths as well when including images with `url("relative/path/to/my_image.png")`.

Any idea what is happening here?  I've exported slides with backslide previously (with v1.2.1 I believe) and did not run into this issue. Thanks!

**Comment by sinedied** [comment]
Yes It seems the PR #14  #16 have broken HTML export for online hosting, see also https://github.com/sinedied/backslide/issues/18.

You can revert to `2.1.0` to have online HTML export working for the moment.

I'm currently working on a complete rewrite of the codebase, that will include a fix for this issue but unfortunately I don't have much free time these days 😉

**Comment by wtbarnes** [comment]
Ok thanks for the update!

As you suggested, I've just rolled back my version (to 1.2.1 actually) when deploying to GH pages and that seems to work fine.

Thanks for building and maintaining backslide. I've found it very useful for the last couple of talks I've given.
