### ISSUE TITLE
dependency on bower

### ISSUE THREAD

**Issue by callmemagnus** [sinedied/backslide#3]
I followed the steps [in the tutorial presentation](https://sinedied.github.io/backslide/#3).

It fails on `bs init` as I don't have bower installed:
```
$ bs init
zsh: command not found: bower
```

Either add 'bower' as dependency and use the local version or add it as a prerequisite to the tool.

What do you think?

**Comment by sinedied** [comment]
Strange, as this tool does not use bower at all, maybe a conflict with another package using the same binary name? What does it show when you type just `bs`? Which os do you use?

**Comment by callmemagnus** [comment]
OS: linux and zsh
```
$ npm -v 
4.4.1
$ node -v
v6.10.0
```

Same problem when running only `bs`.

I also tried to change the shell to bash and then:
```
$ bs
backslide 1.0.2
Usage: bs [init|serve|export|pdf] [options]

Commands:
  i, init            Init new presentation in current directory
    --force          Overwrite existing files
  e, export [files]  Export markdown files to html slides     [default: *.md]
    -o, --output     Output directory                         [default: dist]
  s, serve [dir]     Start dev server for specified directory [default: .]
    -p, --port       Port number to listen on                 [default: 4100]
  p, pdf [files]     Export markdown files to pdf             [default: *.md]
    -o, --output     Output directory                         [default: pdf]
    -d, --decktape   Decktape installation dir                [default: .]
    -w, --wait       Wait time between slides in ms           [default: 1000]
    --verbose        Show Decktape console output

 For pdf export to work, Decktape must be installed.
 See https://github.com/astefanutti/decktape for details.
```

When I use zsh it fails on `bower` not being installed.

This is a bizarre issue...

If I checkout the project and just install its deps, and run `./bin/bs` I don't have the error.

I search a little and found that I was using a bower plugin on oh-my-zsh... Removed that and I can now play with the tool.

Sorry for the noise.
