### ISSUE TITLE
Override the init presentation.md in template

### ISSUE THREAD

**Issue by stu0292** [sinedied/backslide#32]
bs init copies a template and generates an example presentation.md file. The presentation.md file illustrates the default template well but not my custom template. It'd be nice if init would copy presentation.md from the template folder so we don't have to manually overwrite it.

As a workaround I'm using a bash script to copy the files instead.

**Comment by sinedied** [comment]
Sure, that should not be difficult to add.
I'm currently working on a complete rewrite of the app to allow for a lot more flexibility, including the possibility to write plugins, I'll make sure to include that in the pipe 😉

**Comment by sinedied** [comment]
Fixed with `--template` option or `BACKSLIDE_TEMPLATE_DIR` env variable.
