### ISSUE TITLE
bs init overwrites existing presentation md

### ISSUE THREAD

**Issue by SebastianApel** [sinedied/backslide#35]
Hi Team, 

I accidently have run "bs init" a second time. I've lost the source code of my presentation, because the existing "presentation md" was overwritten.  Definitely not cool.

Expected behavious: Write only the files that are missing (if any) - NEVER overwrite existing files.

Looking forward to hearing from you,
Sebastian

**Comment by sinedied** [comment]
I'm sorry for you... That should be simple to fix, I'll do that.
Another idea could be to automatically init a git repo with `bs init` to encourage using version control

**Comment by SebastianApel** [comment]
aweseome, thanks. Do you already have a hypothesis for ETA?
