### ISSUE TITLE
Feature: define metadata that is applied to styles?

### ISSUE THREAD

**Issue by chbndrhnns** [sinedied/backslide#36]
I would like to add a metadata item like this and have it automatically applied in the style.scss file. 

Is this possible now and if not, something you would consider adding to backslide? I am currently missing the exact interplay between sass, bs and remark and have no idea how this could be realized.

```
---
title-image: assets/title.jpg
---
```

**Comment by sinedied** [comment]
I'm not sure I get the point here...

You can use Remark [layout or template slides](https://github.com/gnab/remark/wiki/Markdown#template) to have only 1 reference slide when can apply a given style/template, but there's no way to bridge remark metadata (compiled as JS) with your SCSS stylesheet.

However, I think you can achieve something similar with CSS variables, as your remark file is essentially a glorified HTML template:
```
<!-- in your slides -->
<style>
--title-image: url(assets/title.jpg)
</style>

// in you stylesheet
.some-class {
  background-image: var(--title-image);
}
```

**Comment by chbndrhnns** [comment]
You are right, I had a bad understanding of the template and I did not know about the CSS variables. I assume this will solve my problem.

Thanks!
