### ISSUE TITLE
mime.lookup is not a function when exporting presentations with images

### ISSUE THREAD

**Issue by chbndrhnns** [sinedied/backslide#37]
If `mime` is the node package the backslide relies on for that method call, it seems like changing that call to `mime.getType()` fixes the issue for me.

**Comment by sinedied** [comment]
Arg they updated the package without respecting semver as it's a breaking change 😞
I'll fix that thanks for reporting.

**Comment by sinedied** [comment]
2.3.1 released with the bug fixed.
