### ISSUE TITLE
Can we add "dockerized" way to use it?

### ISSUE THREAD

**Issue by tao12345666333** [sinedied/backslide#39]
Thanks for your work. 

The installation process is very tedious, because of `node-gyp`. I have make a  "dockerized" way to use this, the repo is https://github.com/tao12345666333/backslide

## Creating a new presentation

If you want to create a new presentation in the `$HOME/backslide` directory, you can run `init` by using the backslide Docker image directly:

```
sudo docker run --rm -v $HOME/backslide:/src taobeier/backslide init
```

This command will create a new presentation along with a template directory in the current directory. The template directory is needed for backslide to transform your Markdown files into HTML presentations.

Then edit the file `presentation.md` to get started.

You can create as many markdown presentations as you want in the directory, they will all be based on the same template.

If you want to start a new presentation using your own custom template, you can use `sudo docker run -v $HOME/backslide:/src -v <your_template_dir>:/template taobeier/backslide init --template /template`. You can also set the environment variable `BACKSLIDE_TEMPLATE_DIR` to change the default template used by `bs init`, just pass `-e BACKSLIDE_TEMPLATE_DIR` to docker run.

We can use one line command to use it everywhere.

Can we add one link in README to provide this method?
I will continue to optimize it.

Thanks.

**Comment by sinedied** [comment]
Sure! Just submit a PR and I'll gladly accept it 😃 

As a side note, to reduce `node-gyp` and native plugins install issues, I'm currently doing a complete rewrite of the tool to be more extensible and split features using native code (ie PDF) in separate plugin packages. 😉

**Comment by tao12345666333** [comment]
Yes, I have submit a PR https://github.com/sinedied/backslide/pull/40 .

Your plan looks great to me！

**Comment by sinedied** [comment]
I merged your PR, so I'm closing this issue 😉

**Comment by tao12345666333** [comment]
@sinedied  Thanks.
