### ISSUE TITLE
HTML and PDF Export Fail With Script Tag in Code Block

### ISSUE THREAD

**Issue by kihashi** [sinedied/backslide#43]
When including HTML code snippets in your presentation, including a `</script>` tag prevents the presentation from being exported cleanly.

You can see the effect in the starter presentation.-

 
    ## Learn the tricks

    See the [wiki](https://github.com/gnab/remark/wiki) to learn more of what you can do with .alt[Remark.js]

    ---
    
    ```html 
    <script></script>
    ```

This is what the output looks like from `bs export`

![image](https://user-images.githubusercontent.com/610242/47541290-c240d680-d8a6-11e8-9248-40f614173903.png)

[presentation.zip](https://github.com/sinedied/backslide/files/2517413/presentation.zip)

Attached is the generated HTML file.

The syntax highlighting makes it clear where the error is:

![image](https://user-images.githubusercontent.com/610242/47541499-73477100-d8a7-11e8-9b79-3ee0ba186d60.png)

**Comment by sinedied** [comment]
Yes, this issue was fixed in the `featture/refactor` branch.
In the meanwhile the new rewrite of the project is released (not anytime soon seeing my current free time), you can use it like this:
```
git clone <this repo>
git checkout feature/refactor
npm link
```
And then use the `bs command` normally.

**Comment by kihashi** [comment]
I tried with the `feature/refactor` branch and it seems to be working.
