### ISSUE TITLE
how to include emojis?

### ISSUE THREAD

**Issue by floswald** [sinedied/backslide#47]
hi there,

i was wondering how (if) one could use emojis in a remark.js presentation built from markdown. Ideally :dog: would just render as a dog. any chance? thanks

**Comment by sinedied** [comment]
You can just include emojis as unicode characters, there's nothing special to do 😄 For example copy paste characters from https://emojipedia.org/ and put it in your markdown, and voila.

**Comment by sinedied** [comment]
Also, if you want the same look on all platforms as unicode emoji display is platform-specific, you can use a CSS emoji lib like https://afeld.github.io/emoji-css/ and add them with Remark class shortcut: `.em.em-some-emoji[]`

**Comment by floswald** [comment]
that's great! thanks. presentation looks so much better now! :smile:
