### ISSUE TITLE
Question about "{{ }}" variables

### ISSUE THREAD

**Issue by jldiaz** [sinedied/backslide#49]
This is not an issue, but a question.

I noticed the `index.html` in the `templates`folder contains some expressions in `{{ }}` or even in `{{{ }}}`.

In addition some slides in the default presentation also make use of expressions such as `{{titlte}`.

I was unable to find documentation about this syntax. In particular these are my questions:

* Is this a feature of `backslide` or of `remarkjs`, or even perhaps of some other template library used behind the scenes?
* What is the difference between double or triple braces?
* Which are the variables which can be used in these expressions? Are there some predefined ones? It is possible to define others? Apparently in the "meta" part of each slide new variables can be created, but they appear to be local to that slide. Is it possible to define some "global" variables?

Thank you in advance

**Comment by sinedied** [comment]
Double braces within .md slides are a feature of remarkjs, see https://remarkjs.com/#11. You can define other using slides properties. To have "global" variables, you can use a layout template.

The triple braces special markers for backslide to replace by styles and markdown content, and are predefined.
