### ISSUE TITLE
How to integrate MathJax and LaTeX

### ISSUE THREAD

**Issue by Paul-Yuchao-Dong** [sinedied/backslide#5]
Great package! Makes life a lot easier!

I'm wondering if there's any way I can integrate the MathJax into the presentation?

thanks,

**Comment by sinedied** [comment]
Sure! Here you go, it's explained how to do it on the remark wiki: https://github.com/gnab/remark/wiki/LaTeX-using-MathJax

**Comment by Paul-Yuchao-Dong** [comment]
Many thanks! Sorry for not being clear in my original question. Now I use back slide to create slideshow essentially changing the `.md` file, according to the remark wiki, I need to insert those into the HTML file.

For anyone stumbled on the same issue, please find below my revised index.html (after running `bs init`)

```HTML
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>{{title}}</title>
  {{{style}}}
  <script src="remark.min.js"></script>
  <script src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML&delayStartupUntil=configured" type="text/javascript"></script>  
  <script>
    function create() {
      return remark.create({
        {{{source}}},
        ratio: '16:9',
        highlightLines: true,
        countIncrementalSlides: false,
        highlightStyle: 'github'
      });
    }
    // Setup MathJax
    MathJax.Hub.Config({
        tex2jax: {
        skipTags: ['script', 'noscript', 'style', 'textarea', 'pre']
        }
    });
    MathJax.Hub.Queue(function() {
        $(MathJax.Hub.getAllJax()).map(function(index, elem) {
            return(elem.SourceElement());
        }).parent().addClass('has-jax');
    });

    MathJax.Hub.Configured();
  </script>
</head>
<body onload="slideshow = create()">
</body>
</html>
```

It still raises `$ is not defined` error in the console, but now I can just `\(e^{i\pi} + 1 = 0\)` inline and get math formula and symbol into the slide show!

Great job, developers!

**Comment by sinedied** [comment]
Thanks for sharing!

As for the `$ is not defined` error it's maybe because JQuery is not included, adding a `<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>` tag in the `head` should resolve the issue.

**Comment by Paul-Yuchao-Dong** [comment]
@sinedied just a related question, I did `bs e` to export the presentation set up as above, however, the resulting presentation HMTL failed to material anything. I checked the minimized source file, and didn't find the cdn source, so I think I need to a way to localize the MathJax js, however, it didn't yield so easily. 

What I did was downloaded the MathJax file referenced, and change the above source to  `  <script src="MathJax.js?config=TeX-AMS_HTML&delayStartupUntil=configured" type="text/javascript"></script>`. Then I got errors like 
`MathMenu.js Failed to load resource: the server responded with a status of 404 (Not Found)`, `Failed to load resource: the server responded with a status of 404 (Not Found)` and `Failed to load resource: the server responded with a status of 404 (Not Found)`.

I'm not very fluent in JS tech and I'm not sure what to try next. I'm thinking MathJax must've missed certain dependencies. Any hint would be nice.

Again great project! I think one thing the markdown approach excels at is to get the power of web into the presentation. It is very painful to add mathematical formula to MS PowerPoint...

**Comment by sinedied** [comment]
Just copying the `MathJax.js` file locally is not enough, as there is a lot of dependencies that are lazy loaded.
When running `bs e` all external script are inlined directly in the HTML, to allow offline usage but in the case of MathJax it does not work as many other files are lazy-loaded.

You may try downloading a pre-bundled package here: https://github.com/pkra/MathJax-single-file
or take a look at https://github.com/mathjax/MathJax/wiki/Single-file-built to build your own with the plugins you want.

When I find some time, I'll add an option to `bs export` to disable inlining as a workaround and for people who don't care for offline usage.

EDIT: Just in case, you could also try Katex: https://khan.github.io/KaTeX/ as it has no lazy-loading, it should not have issues with inlining.

**Comment by sinedied** [comment]
@Paul-Yuchao-Dong Just in case, the latest `1.2.0` version of backslide has now a `--no-inline` option to disable script inlining for such cases like MathJax integration.

If you use this option, you may also want to replace the `remark.min.js` script in `template/index.html` by `https://remarkjs.com/downloads/remark-latest.min.js`.
