### ISSUE TITLE
Installation failed on node >12 because of Hummus

### ISSUE THREAD

**Issue by matclab** [sinedied/backslide#70]
According to [hummus#394](https://github.com/galkahana/HummusJS/issues/394), Hummus does not install under node > v12.

With node v13 on Arch linux I've a similar error when trying to install backslide 2.3.7 : 
```
18119 verbose stack Error: hummus@1.0.104 install: `node-pre-gyp install --fallback-to-build $EXTRA_NODE_PRE_GYP_FLAGS`
18119 verbose stack Exit status 118119 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
18119 verbose stack     at EventEmitter.emit (events.js:210:5)
18119 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18119 verbose stack     at ChildProcess.emit (events.js:210:5)
18119 verbose stack     at maybeClose (internal/child_process.js:1023:16)18119 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:281:5)18120 verbose pkgid hummus@1.0.104
```
Any insight on how to build backslide with a recent nodejs ?

**Comment by sinedied** [comment]
Is it still failing? Sometimes hummus package has some latency catching up with newer Node.js (LTS) builds. The build fallback should work though, unless you miss some required tools to build.

I'm considering removing embedded decktape support because of this and make it an optional separate install like it was in the past.

**Comment by matclab** [comment]
Yes.
The problem is tracked in https://github.com/galkahana/HummusJS/issues/394.

Moreover, as noted in https://github.com/galkahana/HummusJS, *galkahana* won't maintain HummusJS anymore which seems to show that the latency to catch node.js will be long this time !

So making decktape optional may be a good move.

**Comment by matclab** [comment]
Thanks a lot !
