### ISSUE TITLE
Accept options to increase embedded images and svg data url sizes.

### ISSUE THREAD

**Issue by mjpieters** [sinedied/backslide#75]
backslide uses web-resource-inliner to inline resources into the exported HTML (when exporting or when directing decktape to generate a PDF).

web-resource-inliner only inlines `<img ...>` and SVG `<use ...>` resources if their resulting data size is 8kb or lower. I need to be able to raise this amount, can an option be added that lets me set the `svg: ...` and `image: ...` options? I'd prefer to set these to `true`, otherwise being able to at least raise the size default would be very helpful.

**Comment by sinedied** [comment]
That's something that may have been overlooked when it was migrated from `inliner` packages, as there used to be no limits on images inlining, so removing the limit there would definitely be ok 😄
