### ISSUE TITLE
Background image in templates dir are not exported

### ISSUE THREAD

**Issue by ToBeHH** [sinedied/backslide#76]
v2.5.0 fixed a lot in exporting to HTML. However, if you have an image in the template folder and reference it in the `style.scss` file like `background-image: url(image.png);`, the image is not exported. Actually the export fails with an error message, that the image is not found. It is shown, when serving the file via `bs serve`.
As a "workaround" you can duplicate the file from templates folder the the main folder.

**Comment by sinedied** [comment]
~~It is expected, as images are intended to be referenced from the presentation path and not from the css path, that may be confusing a bit at first but that way you can put multiple presentations with different images, but using the same template.~~

**Comment by sinedied** [comment]
Closed by #77
