### ISSUE TITLE
An error occurred during pdf conversion: Decktape not found

### ISSUE THREAD

**Issue by cogumbreiro** [sinedied/backslide#8]
Thanks for the great piece of software. This tool really tides up working with remark.

I'm having problems making Decktape 2.0.2 play with backslide 1.2.1. I've tried installing decktape both globally and locally to no avail. Running `bs serve` works fine, but `bs pdf` does not.

Any ideas on what I am doing wrong?

```bash
$ bs 
backslide 1.2.1
...
$ bs pdf

An error occurred during pdf conversion: Decktape not found

$ tail node_modules/decktape/package.json 
  "readme": "ERROR: No README data found!",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/astefanutti/decktape.git"
  },
  "scripts": {
    "start": "node decktape.js"
  },
  "version": "2.0.2"
}
```

**Comment by sinedied** [comment]
You need to specify the decktape installation dir:
```
bs pdf -d <decktape_dir>
```
Decktape was not installable as an npm package back then, but now it seems I can go installing it as a dependency avoiding this manual path setup.

**Comment by cogumbreiro** [comment]
Unfortunately, I'm getting the same error message:
```bash
$ bs pdf -d node_modules/decktape/

An error occurred during pdf conversion: Decktape not found
```

I've got the same results issuing `-d node_modules/`. I've also tried installing decktape system-wide and passing `-d /usr` to no avail.

**Comment by sinedied** [comment]
I'm currently working on `Decktape@2` support, but for now it seems that the new version based on chrome headless has issue with reveal presentations 😞 

In the meantime, it still works with the `1.0.0` release with its custom PhantomJS build: https://github.com/astefanutti/decktape/releases/tag/v1.0.0
