### ISSUE TITLE
CUSTOM MACRO FOR VALORANT NEON BACKSLIDE(REVERSE SLIDE)

### ISSUE THREAD

**Issue by rounbz** [sinedied/backslide#98]
hi , I need to make a custom macro with milliseconds of each of the buttons for backslide neon valorant . Who will do it I will be very grateful

**Comment by rounbz** [comment]
https://www.youtube.com/watch?v=Ofl0JwUl-L4

**Comment by sinedied** [comment]
This is not a place to spam your random requests, use something like https://www.fiverr.com/ for that.
This project has nothing to do with gaming.
